### ISSUE TITLE
tweaks not applying

### ISSUE THREAD

**Issue by binnichtaktiv** [mineek/dirtycowapp#1]
I tried everything. Not only your app. The only apps that work are trolllock and font changer. Hide homebar did work once then I did a respring and the homebar was back again. I tried to disable it again but it didnt work. Hide dock and hide folder background did never work. Not on your app or on others I dont get it... im on iOS 16.1.2 iPhone 11

https://user-images.githubusercontent.com/96953964/210632153-0cdfb671-c6fb-4646-8211-1d869546131d.mp4

**Comment by huami1314** [comment]
Same as you , i am iPhone11 too

**Comment by miyuanbo** [comment]
Probably because of asynchronous execution of the code when the button is tapped?

**Comment by MDX-Tom** [comment]
Probably because of asynchronous execution of the code when the button is tapped? You don't know when the execution is done (perhaps the scrolling lag is the signal that the function returns, however this doesn't work for me either). 
For me, I just keep pressing one of those buttons, until it lags (not responding when I tap the button), then you may press the respring button. This gets it a lot more chance to work for me :)

**Comment by binnichtaktiv** [comment]
> Probably because of asynchronous execution of the code when the button is tapped? You don't know when the execution is done (perhaps the scrolling lag is the signal that the function returns, however this doesn't work for me either). For me, I just keep pressing one of those buttons, until it lags (not responding when I tap the button), then you may press the respring button. This gets it a lot more chance to work for me :)

yessssssssss thank you sooo much not it worked thanks👍🏻😍
